#configMap, Deployment, Service
apiVersion: v1
kind: ConfigMap
metadata: 
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  #labels of deployment resource
  labels:
    app: backend
    project: expense
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      project: expense
      tier: backend
  template:
    metadata:
      labels:
        app: backend
        project: expense
        tier: backend
    spec:
      containers:
      - name: nginx
        image: joindevops/backend:1.0.0
        envFrom:
        - configMapRef:
            name: backend
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    project: expense
    tier: backend
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080