apiVersion: v1
kind: Pod
metadata:
  name: annotations
  buildURL: "https://jenkins.com/expense/job/backend/23"
  imageregistry: "httsp://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx