apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      #soft limit
      requests: 
        memory: "68Mi"
        cpu: "100m"
      #hard limit
      limits:
        requests: "128Mi"
        cpu: "150m"