apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    project: expense
    component: backend-np
    environment: dev
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-np
  labels:
    roject: expense
    component: backend-np
    environment: dev
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx