apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
  #labels of deployment
  labels:
    app: nginx
    tier: frontend
    purpose: deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment 
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment 
    spec:
      containers:
      - name: nginx
        image: sandeep530/deployment:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector: #labels are used as selectors
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32084