apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
    demo: statefulset
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector: 
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      demo: statefulset #has to match .spec.selector.matchLabels
  serviceName: "nginx-headless"
  replicas: 3 # by default 1
  minReadySeconds: 10 # by default 0
  template:
    metadata:
      labels:
        app: nginx
        demo: statefulset #has to match with .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.24
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
    #instead of creating a PVC resource , you can directly provide in statefulset
  volumeClaimTemplates:
  - metadata:
    name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]  
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi