apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-expense"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata: 
  name: efs-dynamic
  labels:
    purpose: "efs-dynamic-demo"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim: 
      claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-lb 
spec:
  type: LoadBalancer
  selector: #labels are used as selectors
    purpose: "efs-static-demo"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32084