apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: {{ .Values.deployment.replicas }} # assume this get changes
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }} # version frequently get changes
        ports:
        - containerPort: 80   