#nodeSelector is the simplest form of node selection constraint in Kubernetes. 
#It tells the scheduler to place a pod only on nodes that match a specific key-value label.

apiVersion: v1
kind: Pod
metadata:
  name: node-selector
  labels:
    purpose: "selector-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
